# Generated by Django 4.1.5 on 2023-01-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.CharField(max_length=30)),
                ('booked', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('booked', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iod.room')),
            ],
        ),
    ]
